version: '3.7'

services:
  
  postgres-staging:
    image: postgres
    env_file: ./.enviroments/.staging.deploy
    volumes:
      - ./staging-data/postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    labels:
      - "com.centurylinklabs.watchtower.enable=false" 

  django-staging:
    container_name: django-staging
    image: acaciaelis/acacia:django-staging
    env_file: ./.enviroments/.staging.deploy
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres-staging
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 

# Prod -----------------------------------------------------

  postgres-production:
    image: postgres
    env_file: ./.enviroments/.production.deploy
    volumes:
      - ./production-data/postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    labels:
      - "com.centurylinklabs.watchtower.enable=false" 

  django-production:
    container_name: django-production
    image: acaciaelis/acacia:django-prod
    env_file: ./.enviroments/.production.deploy
    command: bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - postgres-production
    labels:
      - "com.centurylinklabs.watchtower.enable=true" 

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"