name: CD

on: 
  push:
    branches:
      - develop
      - release/*
      - feature/141-relationship-heroku-actions

jobs:
  env:
    HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup environment
      run: docker build -t acacia-back-heroku .
    - name: Run container
      run: docker run -d -p 8000:8000 acacia-back-heroku
    - name: heroku login
      uses: actions/heroku@master
      with:
        args: "apps"