name: style

on: push

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup enviroment
      run: docker-compose up -d --build
    - name: Run linter
      run: docker exec acacia_backend bash -c "flake8"
